version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command:  >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./env/.postgres
      - ./env/.env
      - ./env/.email
    depends_on:
      - postgres

  postgres:
    restart: always
    image: unnotech/postgres-replication:9.6.6
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ./env/.postgres
      - ./env/.env

volumes:
  postgres-data: